# INSTALLING NUMPY

In [20]:
! pip3 install numpy


In [21]:
import numpy as np

# LEC - 01

In [22]:
# np.array() - 1D and 2D
x = np.array([2, 3, 4, 5])
print(x)
print(type(x))

[2 3 4 5]
<class 'numpy.ndarray'>


In [23]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [24]:
# np.zeros(), np,ones(), np.full()
# print(np.zeros(20))
# print(np.zeros(10, dtype='int32')) #for converting into integer type
# print(np.zeros((3,4)))

# print(np.ones(10))
# print(np.ones((2,2,3,4), dtype='int16'))

print(np.full((4,5), 15))


[[15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]
 [15 15 15 15 15]]


In [25]:
# np.arange(start, stop, step) stop not included 
print(np.arange(10, 5, -1))
print(np.arange(10))

[10  9  8  7  6]
[0 1 2 3 4 5 6 7 8 9]


In [26]:
print(np.arange(1, 11).reshape(2, 5))
print(np.arange(1, 13).reshape(4, 3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
# np.linespace(start, stop, num) divides in equal part of num
print(np.linspace(1, 10, 5))
print(np.linspace(0, 1, 5))

[ 1.    3.25  5.5   7.75 10.  ]
[0.   0.25 0.5  0.75 1.  ]


In [28]:
# np.eye(n)
print(np.eye(4)) # 1. denotes principal diagonal in output matrix
print(np.eye(3,4))
print(np.eye(3,4,k=2)) # k is used for diagonal shift

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [29]:
# .shape, .ndim, .size, ,dtype
x = np.arange(20).reshape(4, 5)
print(x)
print(x.shape) # shape is attribute so we dont use parenthesis 

print(x.shape)

print(x.size)
print(len(x))
print(x.ndim) # .ndim tells number of dimensions 
print(type(x))
print(x.dtype)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(4, 5)
20
4
2
<class 'numpy.ndarray'>
int64


In [30]:
arr = np.arange(4) # use reshape because .shape treats as one dimensional 
print(arr.shape)
print(arr)

(4,)
[0 1 2 3]


In [31]:
# 1D indexing - positive and negative
arr = np.arange(10)
print(arr)
print(arr[-3])
print(arr[-3 : -12 : -2])

[0 1 2 3 4 5 6 7 8 9]
7
[7 5 3 1]


In [32]:
# 2D indexing - arr[row, col], full row, full column 
arr = np.arange(20).reshape(5, 4)
print(arr)
print(arr[2, 2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
10


In [34]:
# 2D slicing - sub-matrix (block)
print(arr)
# print(arr[2:, 1:])
# print(arr[1, 1:])
# print(arr[::4, ::3])
print(arr[1:3:1, 2::-1])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 6  5  4]
 [10  9  8]]


In [17]:
print(arr[1, 1::])

[5 6 7]
