#### Verdict : BROADCASTING SUCCESSFULL! Result shape = (2, 3, 4)

In [2]:
import numpy as np

# Broadcasting

## What is Broadcasting?

Broadcasting lets **NumPy** perform operations on arrays of **different sizes** without writing loops.

NumPy automatically **stretches** the smaller array to match the bigger one (**without actually copying the data**).

---

# Broadcasting Rules

Compare the shapes **from right to left**.

Broadcasting works if:

- ✅ Both dimensions are the same.
- ✅ One of the dimensions is `1`.
- ❌ Otherwise, NumPy raises a `ValueError`.

---

# Example 1: Scalar + Array

```python
import numpy as np

a = np.array([1, 2, 3])

a + 5
```

### Output

```python
array([6, 7, 8])
```

Think of it as:

```text
[1, 2, 3]
+
[5, 5, 5]
```

Result:

```text
[6, 7, 8]
```

---

# Example 2: Matrix + Row Vector

```python
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([10, 20, 30])

A + B
```

### Output

```python
array([[11, 22, 33],
       [14, 25, 36]])
```

The row vector is automatically applied to **every row** of the matrix.

---

# Example 3: Matrix + Column Vector

```python
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [10],
    [20]
])

A + B
```

### Output

```python
array([[11, 12, 13],
       [24, 25, 26]])
```

The column vector is automatically applied to **every column**.

---

# Understanding Shape Comparison

Broadcasting always compares dimensions **from right to left**.

---

## ✅ Example 1

### Shapes

```text
(2, 3)
(3,)
```

Comparison:

```text
3 vs 3 ✅

2 has no matching dimension
→ Treated as 1

2 vs 1 ✅
```

### Result Shape

```text
(2, 3)
```

---

## ✅ Example 2

### Shapes

```text
(4, 1)
(4, 5)
```

Comparison:

```text
1 vs 5 ✅

4 vs 4 ✅
```

### Result Shape

```text
(4, 5)
```

---

## ❌ Example 3

### Shapes

```text
(2, 3)
(2,)
```

Comparison:

```text
3 vs 2 ❌
```

Since neither dimension is equal nor one of them is `1`, broadcasting **fails**.

```python
ValueError: operands could not be broadcast together
```

---

## ❌ Example 4

### Shapes

```text
(2, 3)
(3, 2)
```

Comparison:

```text
3 vs 2 ❌
```

Broadcasting fails immediately.

```python
ValueError: operands could not be broadcast together
```

---

# Easy Trick to Remember

Always compare the **last dimension first**.

For every comparison, ask yourself:

1. Are both dimensions equal?
2. Is one of them `1`?

If **Yes** → Broadcasting works.

If **No** → NumPy raises an error.

---

# Broadcasting Visualization

### Scalar

```text
5

↓

[5 5 5]
```

---

### Row Vector

```text
[10 20 30]

↓

[[10 20 30]
 [10 20 30]]
```

---

### Column Vector

```text
[[10]
 [20]]

↓

[[10 10 10]
 [20 20 20]]
```

---

# Common Uses of Broadcasting

- ➕ Adding a constant to every element
- 📊 Normalizing data
- 🤖 Adding bias in Machine Learning
- ⚡ Fast vectorized computations
- 📈 Image processing
- 🧮 Mathematical operations without loops

---

# Summary Table

| Shapes | Works? | Result Shape |
|---------|--------|--------------|
| `(2,3)` + `(3,)` | ✅ | `(2,3)` |
| `(4,1)` + `(4,5)` | ✅ | `(4,5)` |
| `(2,3)` + `(2,)` | ❌ | Error |
| `(2,3)` + `(3,2)` | ❌ | Error |
| `(5,)` + `()` | ✅ | `(5,)` |

---

# Memory Trick

> **Start from the RIGHT.**

For every pair of dimensions:

- ✅ Same
- ✅ One is `1`
- ❌ Otherwise → Error

---

# One-Line Summary

> **Same or One → Works. Different → Error.**

##### Row Vector: 2D ARRAY HOTI HAI, 1D ARRAY KO WE CANNOT DEFINE AS ROW VECTOR 

[3, 4, 5, 6, 7] shape = (1, 4)

##### Column Vector 

[[3] [4] [5] [6]] shape = (4, 1)

In [3]:
# reshape(rows, cols) - size must match
arr = np.arange(12).reshape(4, -1) # 4 Rows define krdi hai maine, -1 lagane se numpy apne aap columns balance kr lega
# arr2 = arr.reshape(5, -1) this will give error
# print(arr2)
print(arr)
print(arr.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [4]:
arr = np.arange(10) #1D Array
print(arr)
print(arr.shape)
arr1 = arr.reshape(1, -1) #Row Vector
arr2 = arr.reshape(-1, 1) #Column Vector
print("Row Vect", arr1)
print("Column Vect", arr2)

[0 1 2 3 4 5 6 7 8 9]
(10,)
Row Vect [[0 1 2 3 4 5 6 7 8 9]]
Column Vect [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [5]:
# np.newaxis - turn 1D into a row/column vector
arr = np.arange(12)
arr1 = arr[:, np.newaxis] # 1D se 2D me convert ho gaya hai
arr2 = arr[np.newaxis, :]
print(arr)
print(arr1)
print(arr1.shape)
print(arr2)
print(arr2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]
(12, 1)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
(1, 12)


In [8]:
# flatten() vs ravel() - always converts into 1D whether it is 2D, 3D OR ND
arr = np.arange(12).reshape(4, 3)
print(arr)

arr1 = arr.ravel() # Makes Shallow Copy and converts into 1D 
arr1[0] = 99

arr2 = arr.flatten() # Makaes Deep Copy and converts inton 1D
arr2[1] = 100

print("Original Array", arr)

print("Ravel Array", arr1)
print("Flatten Array", arr2)






[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Original Array [[99  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Ravel Array [99  1  2  3  4  5  6  7  8  9 10 11]
Flatten Array [ 99 100   2   3   4   5   6   7   8   9  10  11]


In [ ]:
#Q
M = np.ones((3, 4), dtype = "int32")
N = np.array([10, 20, 30]).reshape(3, 1)
print(M + N)

[[11 11 11 11]
 [21 21 21 21]
 [31 31 31 31]]


In [ ]:
# np.vstack() and np.hstack - Vertical and Horizontal Stacking 
arr1 = np.array([[1, 3, 4], 
                 [2, 3, 5]
                 ])
arr2 = np.array([[5, 6, 7], 
                 [8, 9, 10], 
                 [10, 11, 14]
                 ])
arr4 = np.arange(12).reshape(2, 6)
print(arr1)
print(arr2)
arr3 = np.vstack((arr1, arr2))
print(arr3)
arr5 = np.hstack((arr1, arr4))
print(arr5)


[[1 3 4]
 [2 3 5]]
[[ 5  6  7]
 [ 8  9 10]
 [10 11 14]]
[[ 1  3  4]
 [ 2  3  5]
 [ 5  6  7]
 [ 8  9 10]
 [10 11 14]]
[[ 1  3  4  0  1  2  3  4  5]
 [ 2  3  5  6  7  8  9 10 11]]


In [ ]:
# np.concatenate() with axis
# axis -> 0 vstack
# axis -> 1 hstack 
print(arr1)
print(arr2)
print(arr4)
print(np.concatenate((arr2, arr1), axis = 0))
print(np.concatenate((arr4, arr1), axis = 1))


[[1 3 4]
 [2 3 5]]
[[ 5  6  7]
 [ 8  9 10]
 [10 11 14]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[ 5  6  7]
 [ 8  9 10]
 [10 11 14]
 [ 1  3  4]
 [ 2  3  5]]
[[ 0  1  2  3  4  5  1  3  4]
 [ 6  7  8  9 10 11  2  3  5]]


In [9]:
# np.where(condition, true_val , false_val)

arr = np.array([2,-10,20,-15,-18,10])
arr1 = np.where(arr<0 , 0 , arr) # 0 at -ve elements
print(arr1)
print(arr)

[ 2  0 20  0  0 10]
[  2 -10  20 -15 -18  10]


In [ ]:
arr2 = np.array([20, 40, 55, 75, 80, 35])
arr2 = np.where(arr2 < 40, "Fail", "Pass")
print(arr2)

['Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail']
