In [2]:
import numpy as np


In [4]:
marks = np.array([35, 68, 42, 91, 27, 55])
print(np.where(marks > 50))
print(np.where(marks > 50, 'Pass', 'Fail'))

(array([1, 3, 5]),)
['Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass']


In [4]:
marks = np.array([35, 68, 42, 91, 27, 55])
grades = np.where(marks >= 75, 'A', np.where(marks >= 50, 'B', 'C'))
print(marks)
print(grades)

[35 68 42 91 27 55]
['C' 'B' 'C' 'A' 'C' 'B']


In [9]:
marks = np.array([35, 68, 42, 91, 27, 55])
idx = np.where(marks > 50)[0]
print("Raw Return:", idx)

Raw Return: [1 3 5]


In [6]:
marks = np.zeros((6, 4), dtype=int)

print(marks)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
marks = np.full((6, 4), 35)

print(marks)

[[35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]
 [35 35 35 35]]


In [8]:
roll = np.arange(101, 131, 2)

print(roll)

print(len(roll))

[101 103 105 107 109 111 113 115 117 119 121 123 125 127 129]
15


In [9]:
time = np.linspace(0, 3, 7)

print(time)


[0.  0.5 1.  1.5 2.  2.5 3. ]


In [10]:
table = np.eye(5) * 10

print(table)

[[10.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 10.  0.]
 [ 0.  0.  0.  0. 10.]]


In [11]:
table = np.full((4, 4), 35)

np.fill_diagonal(table, 100)

print(table)

[[100  35  35  35]
 [ 35 100  35  35]
 [ 35  35 100  35]
 [ 35  35  35 100]]
