# Lec - 02

In [22]:
import numpy as np

In [23]:
# np.array([1, 2.5, "Hello"]) #If string then all elements will be string 
print(np.array([1, 2.5, 4])) #If not string but there are number and float then all will become float 
print(np.array([1, 2, 4]))

[1.  2.5 4. ]
[1 2 4]


In [24]:
print(np.array([1, 2.5, 4])) #If not string but there are number and float then all will become float 
print(np.array([1, 2, 4]))

[1.  2.5 4. ]
[1 2 4]


In [25]:
x = np.array([1, 4, 4.3, 4.9, 4.8], dtype='int32') # if we want integer elements in x, then hum log pahele hi assign kr dete hai
print(x)
y = np.array([1, 4, 4.3, 4.9, 4.8])
print(y)
print(y.astype('int32')) # not changing original array - similar function as dtype
y = np.array([1, 4, 4.3, 4.9, 4.8])
print(y)

[1 4 4 4 4]
[1.  4.  4.3 4.9 4.8]
[1 4 4 4 4]
[1.  4.  4.3 4.9 4.8]


In [26]:
# arithmetic - array with scalar, array with array
arr1 = np.arange(10)
print(arr1)
arr1 = arr1 + 5
print(arr1)
print("Multiply", arr1 * 5)
print("Exponent", arr1 ** 2)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
Multiply [25 30 35 40 45 50 55 60 65 70]
Exponent [ 25  36  49  64  81 100 121 144 169 196]


In [27]:
x = np.arange(10)
y = np.arange(11, 21)
print(x)
print(y)
print(x + y) #Length of x and y should be same for this operation to perform successfully

[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19 20]
[11 13 15 17 19 21 23 25 27 29]


In [28]:
x = np.arange(6).reshape(2, 3)
y = np.arange(3).reshape(1, 3)
print(x)
print(y)
print(x + y) #SIZE SAME HONA CHAHIYE 

#Now the next example will throw error
# x = np.arange(6).reshape(3, 2)
# y = np.arange(3).reshape(1, 3)
# print(x)
# print(y)
# print(x + y)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [29]:
# comparison operators - boolean arrays
x = np.arange(5)
y = np.arange(1, 6)
print(x)
print(y)
print(x == y) # Size should be same of the both the arrays 
print(x < y) 


[0 1 2 3 4]
[1 2 3 4 5]
[False False False False False]
[ True  True  True  True  True]


In [30]:
# np.random.seed() + np.random.rand()
print(np.random.rand(5))
print(np.random.rand(5)) # Each time we write random.rand then it will produce 5 different random values between 0 and 1
# 1 is excluded [0, 1)
np.random.seed(3) # making some internal formula static through which random values are coming for random.rand
print(np.random.rand(4)) # in other words seed is making the formula static and now if we write these two code in any computer then random values will be same 

[0.09779742 0.22569063 0.14039778 0.04212994 0.70321834]
[0.6396536  0.01255664 0.49912416 0.89593091 0.32892739]
[0.5507979  0.70814782 0.29090474 0.51082761]


In [31]:
np.random.randn(10) # values are near to 0 such that mean is 0 and standard deviation is 1, but range is not fixed like random.rand

array([-0.2773882 , -0.35475898, -0.08274148, -0.62700068, -0.04381817,
       -0.47721803, -1.31386475,  0.88462238,  0.88131804,  1.70957306])

In [32]:
# np.random.randint(low, high, size), low included and high excluded 
print(np.random.randint(10, 20, 5))
print(np.random.randint(10, 20, 5)) #everytime producing different values 


[11 13 15 18 11]
[18 17 18 11 10]


In [33]:
# np.random.choice(), np.random.shuffle()
lst = [3, 4, 56, 7, 9]
print(np.random.choice(lst, 3)) # It will select 3 random values between list elements 
print(np.random.choice(lst, 3, replace = False)) # replace - false : means elemets wont repeat 
print(np.random.choice(1000, 56)) # Now it will select 56 random values between 0 and 999 

[9 4 9]
[ 4  3 56]
[704 274 372 959 677 184 952 967 165 765 686 545 113   1 853 117 887 970
 747 892 996 611 731 912 511 848 672 912 274 843 183 864 223 141 421 414
 560 957 289 308 497 508 754   2 156  36 858 744 684 176 827 970 182 496
 484 603]


In [34]:
arr = np.arange(10)
np.random.shuffle(arr) # shuffles the elemets randomly between 0 and 9
print(arr)

[3 2 7 4 8 6 0 9 5 1]


### Statistics

In [37]:
# min, max, sum, mean, median, std
arr = np.arange(6).reshape(2, 3)
print(arr)


# print("min", arr.min())
# print("row min", arr.min(axis = 1)) # If axis = 1, means calculating min row-wise
# print("column min", arr.min(axis = 0)) # If axis = 0, means calculating min column-wise


# print("sum", arr.sum())
# print("row sum", arr.sum(axis = 1))
# print("column sum", arr.sum(axis = 0))

print("median of arr", np.median(arr))
# print("standard deviation of arr", arr.std())

[[0 1 2]
 [3 4 5]]
median of arr 2.5


#### Practice Set - 03 - Random & Statistics

In [15]:
# Q1
np.random.seed(42)
x = np.random.randint(1, 7, 10)
print(x)

[4 5 3 5 5 2 3 3 3 5]
